#!/usr/bin/env zsh
# ===============================================================
# Homebrew Environment Setup + Cached Flags + Per-action Timing
# (NO fingerprint; load cache if present, else compute & cache)
# ===============================================================

# ---------- lightweight tracer (NDJSON to $outfile) ----------
: "${HB_TRACE:=0}"   # set HB_TRACE=0 to disable per-action logging
__hb_now() { print -r -- "${EPOCHREALTIME:-$(perl -MTime::HiRes=time -e 'printf "%.6f\n", time()')}"; }
__hb_ms(){ awk -v s="$1" -v e="$2" 'BEGIN{printf "%.5f",(e-s)*1000}' ; }
__hb_log(){
  [[ "$HB_TRACE" = "0" ]] && return 0
  local parent="00-homebrew" phase="$1" start="$2" end="$3" ec="${4:-0}"
  local ms; ms="$(__hb_ms "$start" "$end")"
  local LOGFILE="${outfile:-$HOME/zshrc-log.json}"
  printf '{"kind":"phase","parent":"%s","phase":"%s","start":%.6f,"end":%.6f,"duration_ms":%.5f,"exit_code":%d}\n' \
    "$parent" "$phase" "$start" "$end" "$ms" "$ec" >>"$LOGFILE"
}
__hb_tic(){ _hb_label="$1"; _hb_t0="$(__hb_now)"; }
__hb_toc(){ local ec=${1:-$?}; local _t1="$(__hb_now)"; __hb_log "${_hb_label:-unknown}" "$_hb_t0" "$_t1" "$ec"; unset _hb_label _hb_t0; }

# ---------- locations ----------
local _ZCD="${ZSH_CACHE_DIR:-${XDG_CACHE_HOME:-$HOME/.cache}/zsh}"
local CPUTYPE="${CPUTYPE:-$(uname -m)}"
local _cache_file="$_ZCD/homebrew_flags_${CPUTYPE}.zsh"

# ---------- detect brew prefix by OS/arch (for shellenv bootstrap) ----------
typeset -A brew_prefix
case "$(uname)" in
  Darwin)  brew_prefix[x86_64]="/usr/local"; brew_prefix[arm64]="/opt/homebrew" ;;
  Linux)   brew_prefix[x86_64]="/home/linuxbrew/.linuxbrew" ;;
  FreeBSD) brew_prefix[x86_64]="/usr/local" ;;
esac

# ---------- brew shellenv (timed) ----------
if [[ -x "${brew_prefix[$CPUTYPE]}/bin/brew" ]]; then
  __hb_tic "brew shellenv"
  eval "$("${brew_prefix[$CPUTYPE]}/bin/brew" shellenv 2>/dev/null)"
  __hb_toc $?
fi

# Always export Brewfile path
export HOMEBREW_BUNDLE_FILE="${DOTFILES}/00-homebrew/Brewfile"

# If brew still not found, we’re done quietly
if ! command -v brew >/dev/null 2>&1; then
  return 0
fi

# ---------- helpers ----------
__write_cache() {
  local _file="$1" _ld="$2" _cpp="$3" _pkg="$4"
  local tmp="${_file}.tmp.$$"
  umask 022
  mkdir -p -- "$_ZCD" 2>/dev/null
  {
    print -r -- "# Autogenerated — Homebrew flags cache"
    print -r -- "typeset -g CACHED_LDFLAGS=${(q)_ld}"
    print -r -- "typeset -g CACHED_CPPFLAGS=${(q)_cpp}"
    print -r -- "typeset -g CACHED_PKG_CONFIG_PATH=${(q)_pkg}"
  } >"$tmp"
  mv -f -- "$tmp" "$_file" 2>/dev/null
}

# ---------- try cache first ----------
local _used_cache=0
if [[ -r "$_cache_file" ]]; then
  __hb_tic "load cache"
  source "$_cache_file" 2>/dev/null
  __hb_toc $?
  _used_cache=1
fi

if (( _used_cache )); then
  __hb_tic "export flags (cache)"
  [[ -n "${CACHED_LDFLAGS:-}" ]]        && export LDFLAGS="${LDFLAGS}${LDFLAGS:+ }${CACHED_LDFLAGS}"
  [[ -n "${CACHED_CPPFLAGS:-}" ]]       && export CPPFLAGS="${CPPFLAGS}${CPPFLAGS:+ }${CACHED_CPPFLAGS}"
  [[ -n "${CACHED_PKG_CONFIG_PATH:-}" ]]&& export PKG_CONFIG_PATH="${PKG_CONFIG_PATH}${PKG_CONFIG_PATH:+:}${CACHED_PKG_CONFIG_PATH}"
  __hb_toc $?
  return 0
fi

# ---------- compute flags (only if no cache) ----------
__hb_tic "compute flags"

local -a brew_libs=(xz readline zlib bzip2 openssl@3 tcl-tk openblas lapack openjdk@17)
local -a LD_Flags CPP_Flags PKG_Paths
local LD_PREFIX="-L" CPP_PREFIX="-I" LD_SUFFIX="/lib" CPP_SUFFIX="/include" PKG_SUFFIX="/lib/pkgconfig"

# Base brew prefix once
local _bp; _bp="$(brew --prefix 2>/dev/null)"
if [[ -n "$_bp" ]]; then
  LD_Flags+=("${LD_PREFIX}${_bp}${LD_SUFFIX}")
  CPP_Flags+=("${CPP_PREFIX}${_bp}${CPP_SUFFIX}")
fi

# Add optional libs if present
local library prefix
for library in "${(@)brew_libs}"; do
  prefix="$(brew --prefix "$library" 2>/dev/null)"
  [[ -z "$prefix" || ! -d "$prefix" ]] && continue
  LD_Flags+=("${LD_PREFIX}${prefix}${LD_SUFFIX}")
  CPP_Flags+=("${CPP_PREFIX}${prefix}${CPP_SUFFIX}")
  [[ -d "${prefix}${PKG_SUFFIX}" ]] && PKG_Paths+=("${prefix}${PKG_SUFFIX}")
done
__hb_toc $?

# Xcode SDK include/lib (macOS) — timed but optional
__hb_tic "xcrun sdk paths"
if command -v xcrun >/dev/null 2>&1; then
  local sdk_path; sdk_path="$(xcrun --show-sdk-path 2>/dev/null)"
  if [[ -d "$sdk_path" ]]; then
    LD_Flags+=("${LD_PREFIX}${sdk_path}/usr/lib")
    CPP_Flags+=("${CPP_PREFIX}${sdk_path}/usr/include")
  fi
fi
__hb_toc $?

# Dedup & join
__hb_tic "dedupe & join"
typeset -U LD_Flags CPP_Flags PKG_Paths
local _seg_LDFLAGS="${(j: :)LD_Flags}"
local _seg_CPPFLAGS="${(j: :)CPP_Flags}"
local _seg_PKGCFG="${(j/:/)PKG_Paths}"
__hb_toc $?

# Write cache
__hb_tic "write cache"
__write_cache "$_cache_file" "$_seg_LDFLAGS" "$_seg_CPPFLAGS" "$_seg_PKGCFG"
__hb_toc $?

# Export computed flags
__hb_tic "export flags (fresh)"
[[ -n "$_seg_LDFLAGS" ]] && export LDFLAGS="${LDFLAGS}${LDFLAGS:+ }${_seg_LDFLAGS}"
[[ -n "$_seg_CPPFLAGS" ]] && export CPPFLAGS="${CPPFLAGS}${CPPFLAGS:+ }${_seg_CPPFLAGS}"
[[ -n "$_seg_PKGCFG"   ]] && export PKG_CONFIG_PATH="${PKG_CONFIG_PATH}${PKG_CONFIG_PATH:+:}${_seg_PKGCFG}"
__hb_toc $?

return 0