filetype plugin indent on

set autowrite
set mouse=a

:set number
:set noswapfile

" Brackets Highlighting Colors
hi MatchParen cterm=none ctermbg=black ctermfg=white

" Errors/BadSpellings Higlighing Colors
:highlight clear SpellBad

" CUSOR SETUP
let &t_SI = "\<Esc>]50;CursorShape=1\x7"
let &t_SR = "\<Esc>]50;CursorShape=5\x7"
let &t_EI = "\<Esc>]50;CursorShape=6\x7"

" TAB SETUPS
set tabstop=4       " The width of a TAB is set to 4.
                    " Still it is a \t. It is just that
                    " Vim will interpret it to be having
                    " a width of 4.

set shiftwidth=4    " Indents will have a width of 4

set softtabstop=4   " Sets the number of columns for a TAB

set expandtab       " Expand TABs to spaces