#!/usr/bin/env zsh
source ${HOME}/zsh-defer/zsh-defer.plugin.zsh


_load_plugin() {
  local dir="$1"
  local plugin="$2"
  local defer="${3:-false}"

  if [[ ! -d "$dir" ]]; then
    print -u2 "ERROR: plugin directory not found: $dir"
    return 1
  fi

  fpath+=( "$dir" )
  if [[ "$defer" == "true" ]]; then
    zsh-defer source "$plugin"
  else
    source "$plugin"
  fi
}

_load_plugin \
  "$HOME/Library/Caches/antidote/ohmyzsh/ohmyzsh/plugins/sudo" \
  "$HOME/Library/Caches/antidote/ohmyzsh/ohmyzsh/plugins/sudo/sudo.plugin.zsh" \
  true

_load_plugin \
  "$HOME/Library/Caches/antidote/ohmyzsh/ohmyzsh/plugins/asdf" \
  "$HOME/Library/Caches/antidote/ohmyzsh/ohmyzsh/plugins/asdf/asdf.plugin.zsh" \
  true

_load_plugin \
  "$HOME/Library/Caches/antidote/ohmyzsh/ohmyzsh/custom/plugins/fzf-tab" \
  "$HOME/Library/Caches/antidote/ohmyzsh/ohmyzsh/custom/plugins/fzf-tab/fzf-tab.plugin.zsh" \
  true

_load_plugin \
  "$HOME/Library/Caches/antidote/ohmyzsh/ohmyzsh/plugins/mise" \
  "$HOME/Library/Caches/antidote/ohmyzsh/ohmyzsh/plugins/mise/mise.plugin.zsh" \
  true

_load_plugin \
  "$HOME/Library/Caches/antidote/ohmyzsh/ohmyzsh/plugins/pip" \
  "$HOME/Library/Caches/antidote/ohmyzsh/ohmyzsh/plugins/pip/pip.plugin.zsh" \
  true

_load_plugin \
  "$HOME/Library/Caches/antidote/ohmyzsh/ohmyzsh/plugins/golang" \
  "$HOME/Library/Caches/antidote/ohmyzsh/ohmyzsh/plugins/golang/golang.plugin.zsh" \
  true

_load_plugin \
  "$HOME/Library/Caches/antidote/ohmyzsh/ohmyzsh/plugins/git" \
  "$HOME/Library/Caches/antidote/ohmyzsh/ohmyzsh/plugins/git/git.plugin.zsh" \
  true

_load_plugin \
  "$HOME/Library/Caches/antidote/ohmyzsh/ohmyzsh/custom/plugins/you-should-use" \
  "$HOME/Library/Caches/antidote/ohmyzsh/ohmyzsh/custom/plugins/you-should-use/you-should-use.plugin.zsh" \
  true

_load_plugin \
  "$HOME/Library/Caches/antidote/ohmyzsh/ohmyzsh/plugins/aliases" \
  "$HOME/Library/Caches/antidote/ohmyzsh/ohmyzsh/plugins/aliases/aliases.plugin.zsh" \
  true

_load_plugin \
  "$HOME/Library/Caches/antidote/joshskidmore/zsh-fzf-history-search" \
  "$HOME/Library/Caches/antidote/joshskidmore/zsh-fzf-history-search/zsh-fzf-history-search.plugin.zsh"

_load_plugin \
  "$HOME/Library/Caches/antidote/mattmc3/zfunctions" \
  "$HOME/Library/Caches/antidote/mattmc3/zfunctions/zfunctions.plugin.zsh"

if [[ -d "$HOME/Library/Caches/antidote/romkatv/zsh-bench" ]]; then
  export PATH="$HOME/Library/Caches/antidote/romkatv/zsh-bench:$PATH"
else
  print -u2 "ERROR: plugin directory not found: $HOME/Library/Caches/antidote/romkatv/zsh-bench"
fi
