#!/usr/bin/env zsh
# ===============================================================
# Pyenv Configuration — with Weekly Cached Init (~/.cache/pyenv)
# ===============================================================

PYENV_ROOT="$HOME/.pyenv"
PYENV_CACHE_DIR="$HOME/.cache/pyenv"
PYENV_CACHE_FILE="$PYENV_CACHE_DIR/init_cache.zsh"
PYENV_CACHE_TTL=$((7 * 24 * 60 * 60)) # 7 days

# Ensure cache directory exists
mkdir -p "$PYENV_CACHE_DIR"

# --- Detect if cache is stale ---
cache_stale=true
if [[ -f "$PYENV_CACHE_FILE" ]]; then
  last_update=$(stat -f "%m" "$PYENV_CACHE_FILE" 2>/dev/null || stat -c "%Y" "$PYENV_CACHE_FILE" 2>/dev/null)
  now=$(date +%s)
  (( now - last_update < PYENV_CACHE_TTL )) && cache_stale=false
fi

# --- Rebuild cache if missing or expired ---
if $cache_stale; then
  if command -v pyenv >/dev/null 2>&1; then
    {
      echo "# Auto-generated by 01-pyenv-config.zsh"
      echo "export PYENV_ROOT=\"$PYENV_ROOT\""
      echo "[[ -d \"\$PYENV_ROOT/bin\" ]] && export PATH=\"\$PYENV_ROOT/bin:\$PATH\""
      pyenv init - --no-rehash 2>/dev/null
      pyenv virtualenv-init - 2>/dev/null
    } >| "$PYENV_CACHE_FILE"
    touch "$PYENV_CACHE_FILE"
  fi
fi

# --- Source from cache ---
if [[ -r "$PYENV_CACHE_FILE" ]]; then
  source "$PYENV_CACHE_FILE"
else
  # Fallback to direct init if cache missing or broken
  if command -v pyenv >/dev/null 2>&1; then
    export PYENV_ROOT="$PYENV_ROOT"
    [[ -d "$PYENV_ROOT/bin" ]] && export PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init - --no-rehash 2>/dev/null)"
    eval "$(pyenv virtualenv-init - 2>/dev/null)"
  fi
fi

