alias dot='cd $HOME/.dotfiles/'
alias dotz='cd $HOME/.dotfiles/zsh'
alias szrc='subl $HOME/.dotfiles/zsh/zshrc.symlink'
alias vzrc='vim $HOME/.dotfiles/zsh/zshrc.symlink'
alias rl!='. $HOME/.zshrc'
alias mkcd='foo(){ mkdir -p "$1"; cd "$1" }; foo '
alias touchv='foa(){ touch "$1"; vim "$1" }; foa '
alias touchs='foa(){ touch "$1"; subl "$1" }; foa '
alias touchr='foa(){ touch "$1"; rmate "$1" }; foa '
alias sub='subl -w'
alias lv='vim $_'
alias la='ls -laFh --color=auto'
alias vl='less $_'
alias cv='cat $_'
alias jc='vim $HOME/.virtualenvs/jupyter/etc/jupyter/jupyter_lab_config.py'
alias icloud='cd $HOME/Library/Mobile\ Documents/com\~apple\~CloudDocs/'
alias ppip='noglob python -m pip'
